- lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^#* *UseDNS '
    line: 'UseDNS no'
  notify: service | ssh | reload

- lineinfile:
    state: present
    dest: /etc/sudoers.d/disable-fqdn
    regexp: '^Default.*fqdn'
    line: 'Defaults !fqdn'
    create: yes

- lineinfile:
    state: present
    dest: /etc/hosts
    regexp: "^127.0.0.1 {{ ansible_hostname }}$"
    line: "127.0.0.1 {{ ansible_hostname }}"
    create: yes
